// initial model object
const initModel = {
  customerName: "",
  email: "",
  billTo: "",
  description: "",
  dueDate: "",
  created: "",
  status: "",
  showForm: false,
  nextId: 2,
  editId: null,
  invoices: [
    {
      id: 0,
      customerName: "Jane Doe",
      email: "jane@doe.com",
      billTo: "Jane Doe Inc",
      description: "Did some cool stuff",
      dueDate: "2022-12-29",
      status: "Open",
      showStatusForm: false,
      invoiceLines: [
        {
          lineName: "Setup cool stuff",
          lineHours: 4,
          lineHourlyRate: 25,
          lineAmount: 100,
        },
        {
          lineName: "Some more cool stuff",
          lineHours: 6,
          lineHourlyRate: 25,
          lineAmount: 150,
        },
        {
          lineName: "Some paper work",
          lineHours: 2,
          lineHourlyRate: 25,
          lineAmount: 50,
        },
      ],
      created: "2021-10-05T12:10:35.895+02:00",
      linesAmountTotal: 300,
      linesHoursTotal: 12,
    },
    {
      id: 1,
      customerName: "Slack",
      email: "slack",
      billTo: "slack",
      description: "Some description",
      dueDate: "2021-10-04",
      status: "Due",
      invoiceLines: [
        {
          lineName: "A lot of work",
          lineHours: 24,
          lineHourlyRate: 90,
          lineAmount: 2160,
        },
      ],
      created: "2021-08-01T13:42:07.207+02:00",
      linesAmountTotal: 2160,
      linesHoursTotal: 24,
    },
  ],
  lineName: "",
  lineHours: 0,
  lineHourlyRate: 0,
  invoiceLines: [],
  linesAmountTotal: 0,
};

export default initModel;
